swagger: "2.0"
produces:
  - "application/json"
consumes:
  - "application/json"
basePath: "/"
info:
  title: "微信小程序服务器端"
  version: "latest"

paths:
  /sns/jscode2session:
    post:
      summary: "code2Session"
      description: |
        登录凭证校验。通过[wx.login](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.login.html) 接口获得临时登录凭证 code 后传到开发者服务器调用此接口完成登录流程。更多使用方法详见[小程序登录](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/login.html)。
      consumes: 
        - "application/json"
      produces: 
        - "application/json"
      tags: ["auth"]
      parameters:
        - name: "appid"
          in: "query"
          description: "小程序 appId"
          type: "string"
          required: true
        - name: "secret"
          in: "query"
          description: "小程序 appSecret"
          type: "string"
          required: true
        - name: "js_code"
          in: "query"
          description: "登录时获取的 code"
          type: "string"
          required: true
        - name: "grant_type"
          in: "query"
          description: "授权类型，此处只需填写 authorization_code"
          type: "string"
          required: true
      responses:
        200:
          description: "返回的 JSON 数据包"
          schema:
            type: "object"
            properties:
              openid:
                type: "string"
                description: "用户唯一标识"
              session_key:
                type: "string"
                description: "会话密钥"
              unionid:
                type: "string"
                description: "用户在开放平台的唯一标识符，在满足 UnionID 下发条件的情况下会返回，详见[UnionID 机制说明](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/union-id.html)"
              errcode:
                type: "string"
                description: "错误码"
              errmsg:
                type: "string"
                description: "错误信息"

